---

- name: Setup epel archive
  when: epel_state in ["present", "force"]
  block:
    - name: Setup epel archive repository
      ansible.builtin.template:
        src: epel.repo.j2
        dest: /etc/yum.repos.d/epel.repo
        owner: root
        group: root
        mode: 0644
        backup: no

    - name: Setup epel-testing archive repository
      ansible.builtin.template:
        src: epel_testing.repo.j2
        dest: /etc/yum.repos.d/epel-testing.repo
        owner: root
        group: root
        mode: 0644
        backup: no

- name: Remove epel archive
  when: epel_state == "absent"
  block:
    - name: Setup epel archive repository
      ansible.builtin.file:
        path: /etc/yum.repos.d/epel.repo
        state: absent

    - name: Setup epel-testing archive repository
      ansible.builtin.file:
        path: /etc/yum.repos.d/epel-testing.repo
        state: absent
