---
# Configure epel tasks

- block:
    - name: Setup epel repository package
      package:
        name: >-
          {{ (epel_state in ["present", "force"])
             | ternary(epel_url, "epel-release") }}
        state: >-
          {{ (epel_state == "force")
             | ternary("present", epel_state) }}
      register: epel_package_result
      environment: "{{ proxy_client_environment }}"
      tags:
        - role::epel::install

    - name: Configure epel repositories
      ini_file:
        path: "{{ item.path }}"
        section: "{{ item.section }}"
        option: "enabled"
        value: "{{ (item.enabled) | ternary(1, 0) }}"
        no_extra_spaces: true
      when: epel_state in ["present", "force"]
      register: epel_configure_result
      loop:
        - section: "epel"
          enabled: "{{ epel_enabled }}"
          path: "{{ epel_config_file }}"

        - section: "epel-debuginfo"
          enabled: "{{ epel_debuginfo_enabled }}"
          path: "{{ epel_config_file }}"

        - section: "epel-source"
          enabled: "{{ epel_source_enabled }}"
          path: "{{ epel_config_file }}"

        - section: "epel-testing"
          enabled: "{{ epel_testing_enabled }}"
          path: "{{ epel_testing_config_file }}"

        - section: "epel-testing-debuginfo"
          enabled: "{{ epel_testing_debuginfo_enabled }}"
          path: "{{ epel_testing_config_file }}"

        - section: "epel-testing-source"
          enabled: "{{ epel_testing_source_enabled }}"
          path: "{{ epel_testing_config_file }}"
      loop_control:
        label: "{{ item.section }}"
      tags:
        - role::epel::configure

    - name: Setup epel fact
      set_fact:
        epel_fact:
          state: "{{ epel_state }}"
          enabled: "{{ epel_enabled }}"
          debuginfo_enabled: "{{ epel_debuginfo_enabled }}"
          source_enabled: "{{ epel_source_enabled }}"
          testing_enabled: "{{ epel_testing_enabled }}"
          testing_debuginfo_enabled: "{{ epel_testing_debuginfo_enabled }}"
          testing_source_enabled: "{{ epel_testing_source_enabled }}"
