---
- name: Gather facts
  ansible.builtin.setup:
  when: ansible_facts.distribution is undefined

- ansible.builtin.include_tasks: epel.yml
  when:
    - ansible_facts.distribution | lower != "fedora"
    - epel_configuration_required | bool
