---

- name: Perform epel configuration
  block:
    - name: Setup epel repositories enabled status
      ansible.builtin.include_tasks: enabled.yml

    - name: Setup epel repositories gpg
      ansible.builtin.include_tasks: gpg.yml

    - name: Setup epel repositories mirrors
      ansible.builtin.include_tasks: baseurl.yml
      vars:
        epel_repository_base_url: "{{ epel_repository_local_mirror_url }}"

    - name: Setup epel facts
      ansible.builtin.include_tasks: facts.yml
  tags:
    - role::epel
    - role::epel::configure
