---
# Role configuration tasks

- name: Gather facts
  setup:
  when: ansible_facts.distribution is undefined

- include_tasks: epel.yml
  when:
    - ansible_facts.distribution | lower != "fedora"
    - epel_configuration_required | bool
