---
# Configure epel tasks

- name: Setup proxy client
  ansible.builtin.include_role:
    name: amtega.proxy_client
  vars:
    proxy_client_permanent: no

- ansible.builtin.include_tasks: "epel_archive_{{ epel_state }}.yml"
  when: ansible_facts.distribution_major_version is version("7", "<")

- name: Setup epel for distros >= 7
  when: ansible_facts.distribution_major_version is version("7", ">=")
  block:
    - ansible.builtin.include_tasks: epel_package.yml
      vars:
        epel_message: ""
        epel_package_url: >-
          {{ epel_url
             + "/epel-release-latest-"
             + ansible_facts.distribution_major_version
             + ".noarch.rpm" }}

    - ansible.builtin.include_tasks: epel_package.yml
      when: epel_package_result is failed
      vars:
        epel_message: "(from alternative url)"
        epel_package_url: >-
          {{ epel_url_alternative
             + "/epel-release-latest-"
             + ansible_facts.distribution_major_version
             + ".noarch.rpm" }}

    - name: Assert epel package was installed
      ansible.builtin.assert:
        quiet: yes
        that: >-
          epel_package_result is success or epel_package_result is skipped

- name: Configure epel repositories
  ini_file:
    path: "{{ item.path }}"
    section: "{{ item.section }}"
    option: "enabled"
    value: "{{ (item.enabled) | ternary(1, 0) }}"
    no_extra_spaces: yes
    mode: 0644
  when: epel_state in ["present", "force"]
  register: epel_configure_result
  loop:
    - section: "epel"
      enabled: "{{ epel_enabled }}"
      path: "{{ epel_config_file }}"

    - section: "epel-debuginfo"
      enabled: "{{ epel_debuginfo_enabled }}"
      path: "{{ epel_config_file }}"

    - section: "epel-source"
      enabled: "{{ epel_source_enabled }}"
      path: "{{ epel_config_file }}"

    - section: "epel-testing"
      enabled: "{{ epel_testing_enabled }}"
      path: "{{ epel_testing_config_file }}"

    - section: "epel-testing-debuginfo"
      enabled: "{{ epel_testing_debuginfo_enabled }}"
      path: "{{ epel_testing_config_file }}"

    - section: "epel-testing-source"
      enabled: "{{ epel_testing_source_enabled }}"
      path: "{{ epel_testing_config_file }}"
  loop_control:
    label: "{{ item.section }}"
  tags:
    - role::epel::configure

- name: Setup local facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0775

- name: Setup local fact
  ansible.builtin.template:
    src: epel.fact.j2
    dest: /etc/ansible/facts.d/epel.fact
    mode: 0640
  register: epel_setup_local_fact_result

- name: Refresh local facts # noqa no-handler
  ansible.builtin.setup:
  when: epel_setup_local_fact_result is changed