---

- name: Remove epel archive
  block:
    - name: Setup epel archive repository
      ansible.builtin.file:
        path: /etc/yum.repos.d/epel.repo
        state: absent

    - name: Setup epel-testing archive repository
      ansible.builtin.file:
        path: /etc/yum.repos.d/epel-testing.repo
        state: absent
  tags:
    - role::epel::install