---
# Setup epel pacakge tasks

- name: "Setup epel repository package {{ epel_message }}"
  package:
    name: >-
      {{ (epel_state in ["present", "force"])
         | ternary(epel_package_url, "epel-release") }}
    state: >-
      {{ (epel_state == "force")
         | ternary("present", epel_state) }}
  ignore_errors: yes
  register: epel_package_result
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::epel::install
