---
# Install tasks

- name: setup epel repository package
  package:
    name: >-
      {{ (epel_repository_state == 'present')
            | ternary(epel_repository_url, 'epel-release') }}
    state: "{{ epel_repository_state }}"
  tags:
    - role::epel_repository
    - role::epel_repository::packages
    - role::epel_repository::install
