---
# Setup local fact

- block:
    - name: Setup local facts directory
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Setup local fact
      template:
        src: epel.fact.j2
        dest: /etc/ansible/facts.d/epel.fact
        mode: 0640
  tags:
    - role::epel
    - role::epel::local_fact
