---
# Role tasks

- include_tasks: configure.yml
  when: >-
    ansible_facts.distribution | lower in ["centos", "redhat"]
    and (epel_facts is not defined
         or epel_state != epel_facts.state
         or epel_enabled != epel_facts.enabled
         or epel_debuginfo_enabled != epel_facts.debuginfo_enabled
         or epel_source_enabled != epel_facts.source_enabled
         or epel_testing_enabled != epel_facts.testing_enabled
         or epel_testing_debuginfo_enabled != epel_facts.testing_debuginfo_enabled
         or epel_testing_source_enabled != epel_facts.testing_source_enabled)
  tags:
    - role::epel
