---
# Role tasks

- name: Setup epel
  block:
    - ansible.builtin.include_tasks: configure.yml
      when:
        - epel_management | bool
        - >-
          ansible_facts.distribution is undefined
          or epel_configuration_required | bool
        - ansible_facts.distribution
          | default("centos")
          | lower
          != "fedora"
  tags:
    - role::epel
