---
# Role tasks

- block:
    - include_tasks: configure.yml
      when:
        - >-
          ansible_facts.distribution is undefined
          or epel_configuration_required | bool
        - ansible_facts.distribution
          | default("centos")
          | lower
          in ["centos", "redhat"]

  tags:
    - role::epel
