---
# Role tasks

- name: install epel repository
  include_tasks: install.yml
  tags:
    - role::epel_repository
    - role::epel_repository::install

- name: configure epel repository
  include_tasks: configure.yml
  tags:
    - role::epel_repository
    - role::epel_repository::configure
