---

- name: Setup epel
  block:
    - name: Gather facts
      ansible.builtin.setup:
      when: ansible_facts.distribution is undefined
      tags:
        - always

    - name: Check if epel setup is necessary
      ansible.builtin.set_fact:
        _epel_setup_required: >-
          {{ lookup("template", "setup_required.yml.j2") | from_yaml }}

    - name: Perform epel setup
      ansible.builtin.include_tasks: setup.yml
      when: >-
        ansible_facts.distribution | lower != "fedora"
        and _epel_setup_required | bool
      tags:
        - role::epel::install
        - role::epel::configure
  tags:
    - role::epel
