---

- name: Setup epel
  block:
    - name: Perform epel setup
      ansible.builtin.include_tasks: setup.yml
      when: _epel_setup_required is not defined or epel_state == "force"
      tags:
        - role::epel::install
        - role::epel::configure
  tags:
    - role::epel
