---
# Role tasks

- name: sanity checks
  import_tasks: check.yml
  tags:
    - role::epel
    - role::epel::check

- name: install epel repository
  include_tasks: install.yml
  tags:
    - role::epel
    - role::epel::install

- name: configure epel repository
  include_tasks: configure.yml
  tags:
    - role::epel
    - role::epel::configure
