---

- name: Gather facts
  ansible.builtin.setup:
  when: ansible_facts.distribution is undefined

- name: Check if epel setup is necessary
  ansible.builtin.set_fact:
    _epel_setup_required: >-
      {{ lookup("template", "setup_required.yml.j2") | from_yaml }}

- name: Install and configure epel
  when:
    - ansible_facts.distribution | lower != "fedora"
    - _epel_setup_required | bool
  block:
    - name: Install epel
      ansible.builtin.include_tasks: install.yml
      tags:
        - role::epel
        - role::epel::install

    - name: Configure epel
      ansible.builtin.include_tasks: configure.yml
      when: epel_state in ["present", "force", "absent"]
      tags:
        - role::epel
        - role::epel::configure
