---

dependency:
  name: galaxy
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    dockerfile: ../resources/Dockerfile.centos6.j2
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          epel_state: present
          epel_enabled: 0
          epel_debuginfo_enabled: 0
          epel_source_enabled: 0
          epel_testing_enabled: 0
          epel_testing_debuginfo_enabled: 0
          epel_testing_source_enabled: 0
          epel_config_file: /etc/yum.repos.d/epel.repo
          epel_testing_config_file: /etc/yum.repos.d/epel-testing.repo
verifier:
  name: ansible
