---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: podman
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos6
    dockerfile: ../resources/Dockerfile.centos6.j2
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          epel_state: present
          epel_enabled: no
          epel_debuginfo_enabled: no
          epel_source_enabled: no
          epel_testing_enabled: no
          epel_testing_debuginfo_enabled: no
          epel_testing_source_enabled: no
          epel_modular_enabled: no
          epel_modular_debuginfo_enabled: no
          epel_modular_source_enabled: no
          epel_testing_modular_enabled: no
          epel_testing_modular_debuginfo_enabled: no
          epel_testing_modular_source_enabled: no
          epel_repo_path: /etc/yum.repos.d/epel.repo
          epel_testing_repo_path: /etc/yum.repos.d/epel-testing.repo
      molecule_hosts_centos_6:
        vars:
          python_build_install_dir: /opt/python
          ansible_python_interpreter: /opt/python/bin/python3
verifier:
  name: ansible
