---

- name: Verify
  hosts: molecule_hosts
  tasks:
    - name: Check that all epel repositories are disabled
      ansible.builtin.command: >-
        grep 'enabled=1'
        {{ epel_repo_file_path }}
        {{ epel_testing_config_file }}
      register: check_enabled_options
      failed_when: >-
        check_enabled_options.rc != 1
        or check_enabled_options.stdout | length > 0
      changed_when: no
