---

- name: Verify
  hosts: molecule_hosts
  tasks:
    - name: Check epel repository config file
      ansible.builtin.stat:
        path: "{{ epel_config_file }}"
      register: check_epel_config_file_result

    - name: Check epel testing repository config file
      ansible.builtin.stat:
        path: "{{ epel_testing_config_file }}"
      register: check_epel_testing_config_file_result

    - name: Check epel config files exist
      ansible.builtin.assert:
        that:
          - not check_epel_config_file_result.stat.exists
          - not check_epel_testing_config_file_result.stat.exists

    - name: Check that all epel packages were removed
      ansible.builtin.shell: >-
        set -o pipefail ;
        yum list installed epel* | grep epel
      args:
        warn: no
      register: check_packages
      failed_when: check_packages.stdout | length > 0
      changed_when: no