---

- name: Test epel repository setup
  hosts: molecule_hosts:!molecule_hosts_centos_6
  roles:
    - amtega.epel
  tasks:
    - name: Setup package from epel
      ansible.builtin.yum:
        name: atop
        disablerepo:
          - base
          - extras
          - updates
        state: present
      when:
        - epel_state == "present"
        - epel_enabled != 0

- name: Test epel repository setup in legacy systems
  hosts: molecule_hosts_centos_6
  roles:
    - amtega.epel
  tasks:
    # Ansible yum module does not work in older systems, so we use a direct
    # command
    - name: Setup package from epel usin yum command
      # noqa command-instead-of-module
      ansible.builtin.command: >-
        yum install -y atop
        --disablerepo=base
        --disablerepo=extras
        --disablerepo=updates
      register: yum_result
      changed_when: yum_result.stdout is search("Installed:")
      when:
        - epel_state == "present"
        - epel_enabled != 0
      environment:
        LANGUAGE: en_US
