---

# Repository config files

epel_repo_path: /etc/yum.repos.d/epel.repo
epel_testing_repo_path: /etc/yum.repos.d/epel-testing.repo
epel_modular_repo_path: /etc/yum.repos.d/epel-modular.repo
epel_testing_modular_repo_path: /etc/yum.repos.d/epel-testing-modular.repo

# Repositories

epel_repositories: >-
  {{ (ansible_facts.distribution_major_version is version("7", ">")
     | ternary(epel_base_repositories + epel_modular_repositories,
                epel_base_repositories)) }}

epel_base_repositories:
  - section: epel
    path: "{{ epel_repo_path }}"

  - section: epel-debuginfo
    path: "{{ epel_repo_path }}"

  - section: epel-source
    path: "{{ epel_repo_path }}"

  - section: epel-testing
    path: "{{ epel_testing_repo_path }}"

  - section: epel-testing-debuginfo
    path: "{{ epel_testing_repo_path }}"

  - section: epel-testing-source
    path: "{{ epel_testing_repo_path }}"

epel_modular_repositories:
  - section: epel-modular
    path: "{{ epel_modular_repo_path }}"

  - section: epel-modular-debuginfo
    path: "{{ epel_modular_repo_path }}"

  - section: epel-modular-source
    path: "{{ epel_modular_repo_path }}"

  - section: epel-testing-modular
    path: "{{ epel_testing_modular_repo_path }}"

  - section: epel-testing-modular-debuginfo
    path: "{{ epel_testing_modular_repo_path }}"

  - section: epel-testing-modular-source
    path: "{{ epel_testing_modular_repo_path }}"

 # Repository local mirror

epel_repository_local_mirror_url: >-
  {{ lookup("ansible.builtin.vars",
            "epel_local_mirror%s"
            | format(epel_repository_item.section
                     | regex_replace("-", "_")
                     | regex_replace("^epel(.*)", "\1"))
            , default="") }}
