---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: podman
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos6
    dockerfile: ../resources/Dockerfile.centos6.j2
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:centos7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: quay.io/centos/centos:stream8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          epel_state: present
          epel_enabled: 1
          epel_debuginfo_enabled: 1
          epel_source_enabled: 1
          epel_testing_enabled: 1
          epel_testing_debuginfo_enabled: 1
          epel_testing_source_enabled: 1
          epel_repo_file_path: /etc/yum.repos.d/epel.repo
          epel_testing_config_file: /etc/yum.repos.d/epel-testing.repo
          epel_mirror_url: >-
            {{ (ansible_facts.distribution_major_version is version("8", "<"))
               | ternary('http://mirror.uv.es/mirror/fedora-epel/'
                         + ansible_facts.distribution_major_version
                         + '/x86_64/',
                         'http://mirror.uv.es/mirror/fedora-epel/'
                         + ansible_facts.distribution_major_version
                         + '/Everything/x86_64/'
                        ) }}
          custom_epel_local_mirrors:
            - path: "{{ epel_repo_file_path }}"
              section: epel
              url: "{{ epel_mirror_url }}"
          epel_local_mirrors: >-
            {{ (ansible_facts.distribution_major_version is version("6", "=="))
                | ternary([], custom_epel_local_mirrors) }}
verifier:
  name: ansible
