---

- name: Verify
  hosts: molecule_hosts
  tasks:
    - name: Check epel repository config file
      ansible.builtin.stat:
        path: "{{ epel_repo_file_path }}"
      register: check_epel_repo_file_path_result

    - name: Check epel testing repository config file
      ansible.builtin.stat:
        path: "{{ epel_testing_config_file }}"
      register: check_epel_testing_config_file_result

    - name: Check epel config files exist
      ansible.builtin.assert:
        that:
          - check_epel_repo_file_path_result.stat.exists
          - check_epel_testing_config_file_result.stat.exists

    - name: Check that all epel repositories are enabled
      ansible.builtin.command: >-
        grep 'enabled=0'
        {{ epel_repo_file_path }}
        {{ epel_testing_config_file }}
      register: check_enabled_options
      failed_when: >-
        check_enabled_options.rc != 1
        or check_enabled_options.stdout | length > 0
      changed_when: no
