---

- name: Verify
  hosts: molecule_hosts
  tasks:
    - name: Load role internal variables
      ansible.builtin.include_vars: ../../vars/main.yml

    - name: Check epel repositories config files
      ansible.builtin.stat:
        path: "{{ epel_repository_item.path }}"
      register: check_epel_repo_path_result
      loop: "{{ epel_repositories }}"
      loop_control:
        loop_var: epel_repository_item
        label: "{{ epel_repository_item.section }}"

    - name: Check epel config files exist
      ansible.builtin.assert:
        that: >-
          check_epel_repo_path_result.results
          | map(attribute="stat")
          | selectattr("exists", "equalto", false)
          | list
          | length == 0

    - name: Check that all epel repositories are enabled
      ansible.builtin.command: >-
        grep 'enabled=0'
        {{ epel_repositories
           | map(attribute="path")
           | list
           | join(" ") }}
      register: check_enabled_options
      failed_when: >-
        check_enabled_options.rc != 1
        or check_enabled_options.stdout | length > 0
      changed_when: no
